version: '3.4'
services:
  #microservices
  api-gateway:
    build: './src/ApiGateways/BinRoutingDemo.ApiGateway'
    container_name: api-gateway
  
  payment-provider:
    build: './src/Services/PaymentProvider/PaymentProvider.Api'
    container_name: payment-provider

  reporting:
    build: './src/Services/Reporting/Reporting.Api'
    container_name: reporting
    
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"


