version: '3.4'
services:
  api-gateway:
    image: api-gateway:latest
    build:
      context: .
      dockerfile: src/ApiGateways/BinRoutingDemo.ApiGateway/Dockerfile
    container_name: api-gateway

  payment-provider:
    image: payment-provider:latest
    build:
      context: .
      dockerfile: src/Services/PaymentProvider/PaymentProvider.Api/Dockerfile
    container_name: payment-provider

  reporting:
    image: reporting:latest
    build:
      context: .
      dockerfile: /src/Services/Reporting/Reporting.Api/Dockerfile
    container_name: reporting
    
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul


