version: '3.4'
services:
  api-gateway: 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GlobalConfiguration__ServiceDiscoveryProvider__Host=consul
      - GlobalConfiguration__ServiceDiscoveryProvider__Port=8500
    ports:
      - "80:80"

  payment-provider-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Consul__IP =consul
      - Consul__Port=8500
      - service__address=payment-provider
      - service__port=80
    ports:
      - "80"

  reporting-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Consul__IP =consul
      - Consul__Port=8500
      - service__address=reporting
      - service__port=80
    ports:
      - "80"
  consul:
    ports:
      - "8500"